Fix Python examples
I got a lot of errors that the callback takes 2 arguments but only one
was passed, fe. example.py:

	setting callback
	open
	trying to run
	callback failure !
	TypeError: cb() takes exactly 2 arguments (1 given)
	^Cinterrupted
	0 packets handled
	unbind
	close

Since the first parameter isn't used much anyway so the fix is pretty
straight forward.